version: '3'

services:
  harryseong-microservices:
    container_name: harryseong-microservices
    image: harryseong/harryseong-microservices:0.0.1-SNAPSHOT
    ports:
    - 443:8080
#  harryseong-client:
#    container_name: harryseong-client
#    image: harryseong/harryseong-client:0.0.0
#    ports:
#    - 4203:80
networks:
  default:
    external:
      name: harryseong-microservices_default