version: "3"

# Performs the following:
# 1. Creation of MySQL container with "harryseong" database.
# 2. Creation of Flyway container that runs migrations to initialize "harryseong" database with tables and seed data.
services:
  db:
    container_name: harryseong-mysql
    image: mysql
    environment:
    - MYSQL_DATABASE=harryseong
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_ROOT_HOST=%
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:mysql://db -schemas=harryseong -user=root -password=password -connectRetries=60 migrate
    volumes:
    - ./flyway/sql:/flyway/sql
    depends_on:
    - db